version: '3.7'
services:
  openldap:
    image: osixia/openldap:1.4.0
    container_name: openldap
    hostname: openldap
    domainname: techinterview.com
    volumes:
      - ./openldap:/data/ldif
    environment:
      LDAP_ORGANISATION: My Company
      LDAP_DOMAIN: techinterview.com
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: 123456
      LDAP_CONFIG_PASSWORD: config
      LDAP_BASE_DN: dc=techinterview,dc=com
    ports:
      - "389:389"
    networks:
      - openldap

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports:
      - "80:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - openldap

networks:
  openldap:
    driver: bridge